const char *templateRakefile = 
  "SUMBER = Dir.glob('src/*.c')\n"
  "TUJUAN = 'project.exe'\n"
  "INCLUDE_JALUR = %w( include )\n"
  "BEFRAYOPTS = ''\n"
  "\n"
  "OBJFILE = SUMBER.collect do |s|\n"
  "  ext = s.sub(/\\.c$/, '.o')\n"
  "  File.join('build', File.basename(ext))\n"
  "end\n"
  "GETSRC = proc do |task_name|\n"
  "  ext = task_name.sub(/.o$/, '.c')\n"
  "  File.join('src', File.basename(ext))\n"
  "end\n"
  "\n"
  "rule '.o' => GETSRC do |t|\n"
  "  include_opt = INCLUDE_JALUR.collect { |i| \"-I \" + i } .join(' ')\n"
  "  sh \"gcc -g #{include_opt} -o #{t.name} -c #{t.prerequisites.first}\"\n"
  "end\n"
  "\n"
  "file TUJUAN => OBJFILE do\n"
  "  sh \"gcc #{OBJFILE.join(' ')} #{BEFRAYOPTS} -o #{TUJUAN}\"\n"
  "end\n"
  "\n"
  "task :clean do \n"
  "  sh 'rmdir /S /Q build'\n"
  "  sh 'del ' + TUJUAN\n"
  "end\n"
  "\n"
  "Dir.mkdir('build') unless Dir.exist?('build')\n"
  "task default: TUJUAN\n";